server:
  port: 8083

spring:
  application:
    name: workspace-service

  datasource:
    url: jdbc:postgresql://localhost:5432/workspace_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true