spring:
    application:
          name: workspace-service
    datasource:
            url: jdbc:mysql://localhost:3306/itoffice_db
            username: root
            password: root
server:
  port: 8086